encryptionsalt: v1:RGdp1D1BlJg=:v1:QMhuKT/ygU4/Chgk:Z0vzjxFXosYgK3aI1aoer5TR21GqDA==
config:
  gcp:project: codefarm-p-3d2dea
  app:cloudflareAccountId: 33a38acf2f1943aef0bd5e459903e688
  app:domain: codefarm.cloud
  app:cloudflareZoneId: fa1070a01a1f7dd6823e29fa94118a66
  app:accessTeamDomain: codefarm-production-195f.cloudflareaccess.com
